### ISSUE TITLE
Add d3.forceManyBodyReuse

### ISSUE THREAD

**Issue by rpgove** [vasturiano/d3-force-registry#5]
Great resource! Is it possible to add d3-force-reuse to your registry? Here is an example row you could add to the table:

| Plugin | Description | Code | Examples |
|:---:|---|:---:|---|
| [d3.forceManyBodyReuse](https://github.com/twosixlabs/d3-force-reuse) | Faster inverse-linear (distance) attraction/repulsion force applied to all nodes. Typically used as node repulsion in force-directed graphs for a distributed spread. Runs faster than d3.forceManyBody by reusing approximations. | [d3-force-reuse](https://github.com/twosixlabs/d3-force-reuse) | <ul><li>[Les Miserables graph](https://bl.ocks.org/rpgove/98820c49a3d7fd0d4d628402536aa60b)</li><li>[Speed comparison](https://bl.ocks.org/rpgove/ecee35052e3e81126dcefff134c06dae)</li></ul> |

**Comment by vasturiano** [comment]
@rpgove great! Can you open a PR?
